from . import foundations

class Lower   (foundations.SpaceSeparated,      foundations.Lower): ...
class Upper   (foundations.SpaceSeparated,      foundations.Upper): ...
class Title   (foundations.SpaceSeparated,      foundations.Title): ...
class Sentence(foundations.SpaceSeparated,      foundations.Capitalize): ...
class Snake   (foundations.UnderscoreSeparated, foundations.Lower): ...
class Helter  (foundations.UnderscoreSeparated, foundations.Title): ...
class Macro   (foundations.UnderscoreSeparated, foundations.Upper): ...
class Kebab   (foundations.HyphenSeparated,     foundations.Lower): ...
class Train   (foundations.HyphenSeparated,     foundations.Title): ...
class Cobol   (foundations.HyphenSeparated,     foundations.Upper): ...
class Flat    (foundations.NotSeparated,        foundations.Lower): ...
class Flush   (foundations.NotSeparated,        foundations.Upper): ...
class Pascal  (foundations.NotSeparated,        foundations.Title): ...
class Camel   (foundations.NotSeparated,        foundations.Dromedary): ...
class Dot     (foundations.DotSeparated,        foundations.Lower): ...
class Path    (foundations.SlashSeparated,      foundations.Lower): ...
